---
abstract: 'An OFX client implementation.'
author:
  - 'Brandon Fosdick <bfoz@bfoz.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-OFX
provides:
  Finance::OFX:
    file: lib/Finance/OFX.pm
    version: 2
  Finance::OFX::Account:
    file: lib/Finance/OFX/Account.pm
    version: 2
  Finance::OFX::Institution:
    file: lib/Finance/OFX/Institution.pm
    version: 2
  Finance::OFX::Parse:
    file: lib/Finance/OFX/Parse.pm
    version: 2
  Finance::OFX::Response:
    file: lib/Finance/OFX/Response.pm
    version: 2
  Finance::OFX::Tree:
    file: lib/Finance/OFX/Tree.pm
    version: 2
  Finance::OFX::UserAgent:
    file: lib/Finance/OFX/UserAgent.pm
    version: 2
requires:
  Data::GUID: 0
  HTML::Parser: 0
  HTTP::Date: 0
  LWP: 0
  perl: 5.006
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 2
